title: OS2korrespondance documentation
description: This repository contains documentation for OS2korrespondance
theme: just-the-docs

url: https://os2korrespondance.github.io/OS2korrespondance-docs/

aux_links:
  github.com/os2compliance: https://github.com/OS2korrespondance/OS2korrespondance
  os2.eu/os2compliance: https://www.os2.eu/os2korrespondance

plugins:
  - jekyll-relative-links
